Repository icon-project/icon-service, pull requests merged in 2018-10, with the labels that each got.

#4 if enable SCORE package validator,
  iconservice/iconscore/score_package_validator.py
Labels: bug

#7 Add message parameter on acceptScore() of governance and implement the unit test.
  tests/integrate_test/test_integrate_deploy_audit.py
  tests/integrate_test/test_integrate_deploy_audit_install.py
  tests/integrate_test/test_integrate_deploy_audit_update.py
  tests/integrate_test/test_integrate_deploy_blacklist.py
  tests/integrate_test/test_integrate_deploy_install.py
  tests/integrate_test/test_integrate_deploy_update.py
  tests/integrate_test/test_integrate_deploy_whitelist.py
  tests/integrate_test/test_integrate_event_log.py
  tests/integrate_test/test_integrate_external_call_limit.py
  tests/integrate_test/test_integrate_import_whitelist.py
  tests/integrate_test/test_integrate_revision.py
  tests/integrate_test/test_integrate_scores.py
  tests/integrate_test/test_integrate_service_configuration.py
  tests/integrate_test/test_samples/test_builtin/latest_version/governance/__init__.py
  tests/integrate_test/test_samples/test_builtin/latest_version/governance/governance.py
  tests/integrate_test/test_samples/test_builtin/latest_version/governance/package.json
Labels: enhancement

#13 Make deploying SCORE possible even file/directory existent in a path …
  iconservice/deploy/icon_score_deploy_engine.py
  iconservice/deploy/icon_score_deployer.py
  iconservice/icon_constant.py
  tests/integrate_test/test_integrate_existent_scores.py
  tests/integrate_test/test_integrate_existent_scores_audit.py
  tests/test_icon_score_deployer.py
Labels: bug, enhancement

#23 Refactoring _get_icon_score method in icon_score_context_util
  iconservice/iconscore/icon_score_context_util.py
  tests/test_icon_score_step.py
Labels: enhancement

#25 Rewrite the names of constants in all capital letters with underscores separating words
  iconservice/deploy/icon_score_deploy_engine.py
  iconservice/icon_constant.py
  iconservice/icon_inner_service.py
  iconservice/icon_service_engine.py
  tests/integrate_test/test_integrate_import_whitelist.py
  tests/integrate_test/test_integrate_scores.py
  tests/integrate_test/test_integrate_service_configuration.py
  tests/test_icon_service_engine.py
Labels: enhancement

#27 Fix the bug that has caused when changing constant names
  iconservice/deploy/icon_score_deploy_engine.py
  iconservice/icon_config.py
  iconservice/icon_constant.py
  iconservice/icon_service_engine.py
  tests/integrate_test/test_integrate_base.py
  tests/integrate_test/test_integrate_deploy_whitelist.py
  tests/integrate_test/test_integrate_existent_scores.py
  tests/integrate_test/test_integrate_existent_scores_audit.py
  tests/integrate_test/test_integrate_service_configuration_initial.py
  tests/test_icon_service_engine.py
Labels: bug
