Repository icon-project/icon-service, pull requests merged in 2019-03, with the labels that each got.

#53 IS-270: Improve input data calculating rule
  iconservice/icon_service_engine.py
  iconservice/iconscore/icon_pre_validator.py
  iconservice/iconscore/icon_score_step.py
  tests/base/test_type_converter.py
  tests/base/test_type_converter_func.py
  tests/icon_score/test_icon_pre_validator.py
  tests/integrate_test/test_integrate_deploy_install.py
  tests/integrate_test/test_integrate_estimate_step.py
  tests/test_icon_score_step.py
Labels: enhancement

#88 IS-374: Fix unsafe codes in deployer
  iconservice/deploy/icon_score_deployer.py
  iconservice/icon_constant.py
  iconservice/iconscore/icon_score_class_loader.py
  tests/sample/nodir_nopackage.zip
  tests/sample/normal_nopackage.zip
  tests/test_icon_score_deployer.py
Labels: enhancement

#93 IS-381: Refactor ContainerDB
  iconservice/iconscore/icon_container_db.py
  iconservice/utils/__init__.py
Labels: enhancement

#91 IS-373: implement recover_key() and create_address_with_key()
  iconservice/__init__.py
  iconservice/iconscore/icon_score_base2.py
  tests/test_icon_score_api.py
Labels: enhancement

#92 IS-377: Reject non-string values of input data field on pre-validating
  iconservice/iconscore/icon_pre_validator.py
  tests/icon_score/test_icon_pre_validator.py
  tests/integrate_test/test_integrate_base.py
  tests/integrate_test/test_integrate_deploy_install.py
  tests/integrate_test/test_integrate_score_method_parameters_type.py
  tests/integrate_test/test_integrate_service_configuration.py
Labels: enhancement

#99 IS-403: Fix memory leak for IconScoreContext
  iconservice/icon_inner_service.py
  iconservice/icon_service_engine.py
  iconservice/iconscore/icon_score_context.py
  tests/test_icon_score_result.py
  tests/test_icon_score_step.py
Labels: bug

#98 IS-398: Add unit tests for IconScoreEngine
  iconservice/iconscore/icon_score_engine.py
  tests/integrate_test/test_integrate_estimate_step.py
  tests/test_icon_score_engine.py
Labels: enhancement

#47 Add unit tests for IconScoreDeployEngine
  tests/test_icon_score_deploy_engine.py
Labels: low priority
